spring.application.name=url



spring.jpa.show.sql=true

# Serialize LocalDateTime as ISO string instead of array [2026,6,21,14,30,0]
spring.jackson.serialization.write-dates-as-timestamps=false
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8083}